### ISSUE TITLE
Release, GraphViz updates?

### ISSUE THREAD

**Issue by mohawk2** [eserte/graphviz-makefile#3]
Thanks for merging #2! Are you open to further updates to tweak the generated GraphViz output, and also incorporating improvements "inspired by" (copied from) Makefile::GraphViz?

I'm also thinking about adding a layer to this code that makes a Graphviz "description" that can then be fed to GraphViz, but can be automatically tested (I'd also want to make a simple CLI display mode for that). Thoughts welcome!

By the by, the functionality of `guess_external_makes` is one I already had in mind to incorporate into `Make`, inspired by Peter Miller's "recursive make considered harmful" paper, so if you're amenable I will also do that and update this code to use that. Do you have any test Makefiles we could use to check correct functioning? Or shall I be bold and go straight for PDL?

Finally, what do you think about pushing out at least a dev-release and hopefully a main one with just the Make updates? It seems a pity to have fixed it but not release it :-)

**Comment by eserte** [comment]
1.17_50.is out.

As for the other suggestions: this all sounds good, and it sounds like you want to have co-maint permissions ;-)

**Comment by mohawk2** [comment]
Well, I'm amenable :-D PAUSE ID: ETJ

**Comment by eserte** [comment]
You are now co-maint.

**Comment by mohawk2** [comment]
Thank you! My thinking was this is very much your creation, so rather than operate off a fork, are you open to adding me as a collaborator (not sure of right terminology) on this repo?

**Comment by mohawk2** [comment]
Thanks for collaboration! Are you happy with the proposed direction?

**Comment by eserte** [comment]
Yes, go on!

**Comment by mohawk2** [comment]
All systems go!
